/*
 * Copyright (C) 2017 arx iT
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package ch.asit_asso.extract.plugins.common;

import java.util.Calendar;



/**
 * Interface for communicating a request result to a connector plugin for export.
 *
 * @author Florent Krin
 */
public interface ITaskProcessorRequest {

    int getId();



    /**
     * Obtains the string identifying the parent order of this request.
     *
     * @return the order identifier
     */
    String getOrderGuid();



    /**
     * Obtains the string identifying the product corresponding to this request.
     *
     * @return the product identifier
     */
    String getProductGuid();



    /**
     * Obtains the comment added to this request result.
     *
     * @return the remark
     */
    String getRemark();



    /**
     * Obtains the final state of this request.
     *
     * @return the status
     */
    String getStatus();



    /**
     * Obtains the path of the folder that contains the files generated by the request processing.
     *
     * @return the absolute path of the request output folder
     */
    String getFolderOut();



    /**
     * Obtains the name of the order recipient.
     *
     * @return the client name
     */
    String getClient();



    /**
     * Obtains the string that identifies the order recipient.
     *
     * @return the client GUID
     */
    String getClientGuid();



    /**
     * Obtains when the request processing completed.
     *
     * @return the end date
     */
    Calendar getEndDate();



    /**
     * Obtains the path of the folder containing the files used to process the request.
     *
     * @return the absolute path of the request input folder
     */
    String getFolderIn();



    /**
     * Obtains the user-friendly name of the parent order.
     *
     * @return the order label
     */
    String getOrderLabel();



    /**
     * Obtains the non-standard parameters intended for the task plugins.
     *
     * @return the parameters as a JSON string
     */
    String getParameters();



    /**
     * Obtains the coordinates of the extraction polygon.
     *
     * @return the extraction polygon coordinates as a JSON string
     */
    String getPerimeter();



    /**
     * Obtains the user-friendly name of the product matching this request.
     *
     * @return the product label
     */
    String getProductLabel();



    /**
     * Obtains the organization that ordered the product for this request.
     *
     * @return the name of the organism
     */
    String getOrganism();



    /**
     * Obtains the string that identifies the organization that ordered the product for this request.
     *
     * @return the GUID of the organism
     */
    String getOrganismGuid();



    /**
     * Obtains whether the administrator stopped the processing of this request.
     *
     * @return <code>true</code> if this request has been rejected by the administrator
     */
    boolean isRejected();



    /**
     * Obtains when the processing of this request began.
     *
     * @return the start date
     */
    Calendar getStartDate();



    /**
     * Obtains the name of the third party involved in the order.
     *
     * @return the third party name
     */
    String getTiers();


    /**
     * Obtains the surface area of the extraction.
     *
     * @return the surface area value as a string
     */
    String getSurface();

}
